Repository Bibim-SCIT/Bibim_PJT, pull requests merged in 2025-03, with the labels that each got.

#183 fix: dm 사진 안뜨는 버그 해결
  Front-End/bibim/vite/src/views/dm/ChatComponent.jsx
  Front-End/bibim/vite/src/views/dm/index.jsx
Labels: bug

#184 feat: 자료실 검색 추가, 로고 변경
  Front-End/bibim/vite/src/api/workdata.js
  Front-End/bibim/vite/src/assets/images/icons/bibim250311.png
  Front-End/bibim/vite/src/assets/images/icons/bibim250311_2.png
  Front-End/bibim/vite/src/layout/MainLayout/Header/ProfileSection/index.jsx
  Front-End/bibim/vite/src/store/workspaceStore.js
  Front-End/bibim/vite/src/ui-component/Logo.jsx
  Front-End/bibim/vite/src/views/schedule/gantt/index.jsx
  Front-End/bibim/vite/src/views/workdata/components/FileTable.jsx
  Front-End/bibim/vite/src/views/workdata/index.jsx
Labels: enhancement

#177 feat:mypage-workdata
  Back-End/src/main/java/net/scit/backend/config/SecurityConfig.java
  Back-End/src/main/java/net/scit/backend/mypage/controller/MyPageController.java
  Back-End/src/main/java/net/scit/backend/mypage/dto/AllWorkspaceDataDTO.java
  Back-End/src/main/java/net/scit/backend/mypage/service/MyPageService.java
  Back-End/src/main/java/net/scit/backend/mypage/service/impl/MyPageServiceImpl.java
  Back-End/src/main/java/net/scit/backend/schedule/repository/MediumTagRepository.java
  Back-End/src/main/java/net/scit/backend/schedule/repository/ScheduleTagRepository.java
  Back-End/src/main/java/net/scit/backend/schedule/service/impl/ScheduleServiceImpl.java
  Back-End/src/main/java/net/scit/backend/workdata/repository/WorkdataRepository.java
  Back-End/src/main/java/net/scit/backend/workspace/repository/WorkspaceMemberRepository.java
Labels: enhancement

#191 Style/modals4 모달 디자인 통일
  Front-End/bibim/vite/src/layout/MainLayout/Sidebar/MenuCard/index.jsx
  Front-End/bibim/vite/src/views/dm/DmChat.css
  Front-End/bibim/vite/src/views/dm/components/UserLoading.jsx
  Front-End/bibim/vite/src/views/mypage_update/myInfoUpdate.jsx
  Front-End/bibim/vite/src/views/schedule/components/ScheduleCreateModal.jsx
  Front-End/bibim/vite/src/views/schedule/components/ScheduleEditModal.jsx
  Front-End/bibim/vite/src/views/ws-channel/ChatComponent.jsx
  Front-End/bibim/vite/src/views/ws-setting/components/WsInviteModal.jsx
  Front-End/bibim/vite/src/views/ws-setting/components/WsSettingModal.jsx
Labels: enhancement

#193 Feat/youtube update
  Front-End/bibim/vite/src/views/dm/index.jsx
  Front-End/bibim/vite/src/views/ws-channel/ChatComponent.css
  Front-End/bibim/vite/src/views/ws-channel/ChatComponent.jsx
Labels: enhancement

#194 feat: 자료실 미리보기 및 이미지 추가
  Front-End/bibim/vite/src/views/workdata/components/FileCardView.jsx
  Front-End/bibim/vite/src/views/workdata/components/FileTable.jsx
Labels: enhancement

#192 feat: schedule/tag modal
  Front-End/bibim/vite/src/api/tag.js
  Front-End/bibim/vite/src/views/schedule/components/TagCreateModal.jsx
  Front-End/bibim/vite/src/views/schedule/components/TagEditModal.jsx
  Front-End/bibim/vite/src/views/schedule/index.jsx
Labels: enhancement

#195 feat: 회원가입 폼 및 dm 채팅 로딩 추가
  Front-End/bibim/vite/src/ui-component/cards/MainCard.jsx
  Front-End/bibim/vite/src/views/dm/components/ChatLoading.jsx
  Front-End/bibim/vite/src/views/dm/index.jsx
  Front-End/bibim/vite/src/views/pages/auth-forms/AuthRegister.jsx
  Front-End/bibim/vite/src/views/pages/authentication/AuthCardWrapper.jsx
Labels: enhancement

#196 refactor: 자료실 전체조회 시 파일 이름, url 등 출력
  Back-End/src/main/java/net/scit/backend/workdata/service/impl/WorkdataServiceImpl.java
Labels: refactor

#198 Style/chat css DM css 대폭 수정
  Front-End/bibim/vite/src/views/dm/DmChat.css
  Front-End/bibim/vite/src/views/dm/DmDesign.css
  Front-End/bibim/vite/src/views/dm/index.jsx
Labels: enhancement

#202 채널 dm 표시 시간 수정
  Back-End/src/main/java/net/scit/backend/channel/DTO/MessageDTO.java
  Back-End/src/main/java/net/scit/backend/channel/service/impl/ChannelServiceImpl.java
  Front-End/bibim/vite/package-lock.json
  Front-End/bibim/vite/package.json
  Front-End/bibim/vite/src/views/dm/index.jsx
  Front-End/bibim/vite/src/views/ws-channel/ChatComponent.jsx
  Front-End/bibim/vite/yarn.lock
Labels: enhancement

#199 feat: 워크스페이스 채널 내 팀원 접속현황 조회
  Back-End/src/main/java/net/scit/backend/config/SecurityConfig.java
  Back-End/src/main/java/net/scit/backend/member/controller/MemberController.java
  Back-End/src/main/java/net/scit/backend/member/dto/WorkspaceChannelLoginStatusDTO.java
  Back-End/src/main/java/net/scit/backend/member/service/impl/MemberServiceImpl.java
  Back-End/src/main/java/net/scit/backend/workspace/controller/WorkspaceChannelController.java
  Back-End/src/main/java/net/scit/backend/workspace/controller/WorkspaceController.java
  Back-End/src/main/java/net/scit/backend/workspace/repository/WorkspaceMemberRepository.java
  Back-End/src/main/java/net/scit/backend/workspace/service/WorkspaceChannelService.java
  Back-End/src/main/java/net/scit/backend/workspace/service/WorkspaceService.java
  Back-End/src/main/java/net/scit/backend/workspace/service/impl/WorkspaceChannelServiceImpl.java
  Back-End/src/main/java/net/scit/backend/workspace/service/impl/WorkspaceServiceImpl.java
Labels: enhancement, refactor

#205 feat: 일정관리 내 태그 관련 기능 추가
  Front-End/bibim/vite/src/api/schedule.js
  Front-End/bibim/vite/src/views/schedule/components/GanttChart.jsx
  Front-End/bibim/vite/src/views/schedule/components/ScheduleCreateModal.jsx
  Front-End/bibim/vite/src/views/schedule/components/ScheduleDetailModal.jsx
  Front-End/bibim/vite/src/views/schedule/components/ScheduleEditModal.jsx
  Front-End/bibim/vite/src/views/schedule/components/TagCreateModal.jsx
  Front-End/bibim/vite/src/views/schedule/index.jsx
Labels: enhancement

#204 refactor: 알림 URL 매핑 리팩토링 및 SSE 로직 변경
  Back-End/src/main/java/net/scit/backend/notification/controller/NotificationController.java
  Back-End/src/main/java/net/scit/backend/notification/service/NotificationService.java
  Back-End/src/main/java/net/scit/backend/notification/service/impl/NotificationServiceImpl.java
  Back-End/src/main/java/net/scit/backend/workdata/controller/WorkdataController.java
  Back-End/src/main/java/net/scit/backend/workspace/listener/WorkspaceChannelEventListener.java
Labels: enhancement, refactor

#203 refactor: schedule/kanban
  Back-End/src/main/java/net/scit/backend/workspace/repository/WorkspaceMemberRepository.java
  Front-End/bibim/vite/src/api/schedule.js
  Front-End/bibim/vite/src/views/dm/DmChat.css
  Front-End/bibim/vite/src/views/dm/index.jsx
  Front-End/bibim/vite/src/views/schedule/components/KanbanBoard.jsx
  Front-End/bibim/vite/src/views/ws-channel/ChatComponent.jsx
  Front-End/bibim/vite/src/views/ws-setting/components/WsUserRoleManagement.jsx
Labels: refactor

#206 Feat/user status
  Front-End/bibim/vite/src/api/workspaceApi.js
  Front-End/bibim/vite/src/api/workspaceMember.js
  Front-End/bibim/vite/src/views/dm/DmDesign.css
  Front-End/bibim/vite/src/views/dm/index.jsx
  Front-End/bibim/vite/src/views/ws-channel/ChatComponent.css
  Front-End/bibim/vite/src/views/ws-channel/ChatComponent.jsx
Labels: enhancement

#207 Fix/ws user management
  Front-End/bibim/vite/src/views/ws-setting/components/WsUserRoleManagement.jsx
Labels: bug, refactor

#208 feat: 프론트 채널 및 dm 파일 다운로드 수정
  Back-End/src/main/java/net/scit/backend/channel/DTO/MessageDTO.java
  Back-End/src/main/java/net/scit/backend/channel/entity/MessageEntity.java
  Back-End/src/main/java/net/scit/backend/channel/service/impl/ChannelServiceImpl.java
  Front-End/bibim/vite/src/views/dm/index.jsx
  Front-End/bibim/vite/src/views/ws-channel/ChatComponent.jsx
Labels: bug

#209 refactor/schedult-get-tag
  Back-End/src/main/java/net/scit/backend/schedule/dto/ScheduleDTO.java
  Back-End/src/main/java/net/scit/backend/schedule/service/impl/ScheduleServiceImpl.java
Labels: refactor

#210 refactor: SSE 로직 변경에 따른 Map 기반 전체 이벤트 리스너 변경
  Back-End/src/main/java/net/scit/backend/member/listener/MemberEventListener.java
  Back-End/src/main/java/net/scit/backend/schedule/listener/ScheduleEventListener.java
  Back-End/src/main/java/net/scit/backend/workdata/listener/WorkdataEventListener.java
  Back-End/src/main/java/net/scit/backend/workspace/listener/WorkspaceChannelEventListener.java
  Back-End/src/main/java/net/scit/backend/workspace/listener/WorkspaceEventListener.java
Labels: refactor

#211 fix: 프론트 채널 오류 해결
  Back-End/src/main/java/net/scit/backend/channel/service/impl/ChannelServiceImpl.java
  Back-End/src/main/java/net/scit/backend/dm/service/impl/DmServiceImpl.java
  Front-End/bibim/vite/src/views/dm/index.jsx
  Front-End/bibim/vite/src/views/ws-channel/ChatComponent.css
  Front-End/bibim/vite/src/views/ws-channel/ChatComponent.jsx
Labels: bug

#212 feat: 자료실 등, 프론트엔드 여러기능 추가
  Front-End/bibim/vite/src/api/workdata.js
  Front-End/bibim/vite/src/views/dm/index.jsx
  Front-End/bibim/vite/src/views/workdata/index.jsx
Labels: enhancement

#213 feat: env ignore추가 및 번역함수
  .gitignore
  Front-End/bibim/vite/.env
  Front-End/bibim/vite/.gitignore
  Front-End/bibim/vite/src/api/translate.js
  Front-End/bibim/vite/src/views/dm/index.jsx
Labels: enhancement

#214 Feat/mypage schedule 마이페이지 내 스케줄 불러오기 css + 버그수정
  Back-End/src/main/java/net/scit/backend/mypage/controller/MyPageController.java
  Back-End/src/main/java/net/scit/backend/mypage/service/impl/MyPageServiceImpl.java
  Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/NotificationList.jsx
  Front-End/bibim/vite/src/views/dm/components/ChatLoading.jsx
  Front-End/bibim/vite/src/views/dm/index.jsx
  Front-End/bibim/vite/src/views/mypage/component/MyCalendar.jsx
  Front-End/bibim/vite/src/views/mypage/component/MyGanttChart.jsx
  Front-End/bibim/vite/src/views/mypage/component/mySchedule.jsx
  Front-End/bibim/vite/src/views/mypage/index.jsx
Labels: bug, enhancement

#215 refactor/get-my-schedule
  Back-End/Dockerfile
  Back-End/src/main/java/net/scit/backend/config/SecurityConfig.java
  Back-End/src/main/java/net/scit/backend/mypage/service/impl/MyPageServiceImpl.java
  Back-End/src/main/resources/appication.yml
Labels: enhancement

#216 코드 최적화
  .gitignore
  Back-End/src/main/java/net/scit/backend/channel/handler/StompHandler.java
  Back-End/src/main/java/net/scit/backend/channel/service/impl/ChannelServiceImpl.java
  Back-End/src/main/java/net/scit/backend/component/S3Uploader.java
  Back-End/src/main/java/net/scit/backend/component/S3UploaderBackUp.java
  Back-End/src/main/java/net/scit/backend/dm/controller/DMController.java
  Back-End/src/main/java/net/scit/backend/dm/service/impl/DmServiceImpl.java
  Back-End/src/main/java/net/scit/backend/jwt/JwtAuthenticationFilter.java
  Back-End/src/main/java/net/scit/backend/jwt/JwtTokenProvider.java
  Back-End/src/main/java/net/scit/backend/member/controller/MemberController.java
  Back-End/src/main/java/net/scit/backend/member/service/impl/MemberServiceImpl.java
  Back-End/src/main/java/net/scit/backend/mypage/service/impl/MyPageServiceImpl.java
  Back-End/src/main/java/net/scit/backend/oauth/service/impl/OAuthServiceImpl.java
  Back-End/src/main/java/net/scit/backend/workspace/service/impl/WorkspaceChannelServiceImpl.java
  Back-End/src/main/java/net/scit/backend/workspace/service/impl/WorkspaceServiceBackUp.txt
Labels: refactor

#217 refactor: 백엔드 읽은 알림 메서드 추가 및 최적화, 프론트엔드 절반 정도 구현
  Back-End/src/main/java/net/scit/backend/notification/controller/NotificationController.java
  Back-End/src/main/java/net/scit/backend/notification/repository/NotificationRepository.java
  Back-End/src/main/java/net/scit/backend/notification/service/NotificationService.java
  Back-End/src/main/java/net/scit/backend/notification/service/impl/NotificationServiceImpl.java
  Front-End/bibim/vite/package-lock.json
  Front-End/bibim/vite/package.json
  Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/NotificationList.jsx
  Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/index.jsx
  Front-End/bibim/vite/yarn.lock
Labels: enhancement, refactor

#218 feat: dm 페이지 번역기능 추가
  Front-End/bibim/vite/src/api/translate.js
  Front-End/bibim/vite/src/views/dm/DmDesign.css
  Front-End/bibim/vite/src/views/dm/index.jsx
  Front-End/bibim/vite/src/views/workdata/components/FileCardView.jsx
  Front-End/bibim/vite/src/views/workdata/components/FileTable.jsx
Labels: enhancement

#221 feat: 채널페이지 컴퍼넌트 분리
  Front-End/bibim/vite/src/routes/MainRoutes.jsx
  Front-End/bibim/vite/src/views/dm/index.jsx
  Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.css
  Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.jsx
  Front-End/bibim/vite/src/views/ws-channel/index.jsx
Labels: enhancement

#224 feat: 채널 선택 drawer 및 기본 채널 입장 설정
  Back-End/src/main/java/net/scit/backend/workspace/controller/WorkspaceChannelController.java
  Front-End/bibim/vite/src/api/channel.js
  Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.jsx
  Front-End/bibim/vite/src/views/ws-channel/index.jsx
Labels: enhancement

#225 feat: 읽지 않은 알림 개수 아이콘 우상단 표시
  Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/index.jsx
Labels: enhancement

#226 feat: 채널 관련 채널 CRUD 기능, 로딩화면 추가
  Front-End/bibim/vite/src/api/channel.js
  Front-End/bibim/vite/src/assets/images/lottie/chatload.json
  Front-End/bibim/vite/src/views/ws-channel/components/ChannelCreateModal.jsx
  Front-End/bibim/vite/src/views/ws-channel/components/ChannelEditModal.jsx
  Front-End/bibim/vite/src/views/ws-channel/components/ChannelLoading.jsx
  Front-End/bibim/vite/src/views/ws-channel/components/ChannelLoading2.jsx
  Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.css
  Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.jsx
  Front-End/bibim/vite/src/views/ws-channel/index.jsx
Labels: enhancement

#227 refactor: 알림 페이지 무한 스크롤 기능에서 기존 리스트 형식으로의 변환
  Back-End/src/main/java/net/scit/backend/notification/controller/NotificationController.java
  Back-End/src/main/java/net/scit/backend/notification/repository/NotificationRepository.java
  Back-End/src/main/java/net/scit/backend/notification/service/NotificationService.java
  Back-End/src/main/java/net/scit/backend/notification/service/impl/NotificationServiceImpl.java
  Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/index.jsx
Labels: refactor

#228 Feat/mypage-schedule 마이페이지 워크스페이스 조회
  Front-End/bibim/vite/src/api/mypage.js
  Front-End/bibim/vite/src/views/mypage/component/MyGanttChart.jsx
  Front-End/bibim/vite/src/views/mypage/component/MyWorkspaces copy.jsx
  Front-End/bibim/vite/src/views/mypage/component/MyWorkspaces.jsx
  Front-End/bibim/vite/src/views/mypage/component/mySchedule.jsx
  Front-End/bibim/vite/src/views/mypage/index.jsx
  Front-End/bibim/vite/src/views/ws-select/components/CreateWorkspaceModal.jsx
Labels: enhancement

#230 fix: 채널 로딩 속도 개선
  Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.jsx
Labels: refactor

#233 fix: 채널 생성시 생성한 ID와 채널 이름 반환
  Back-End/src/main/java/net/scit/backend/workspace/controller/WorkspaceChannelController.java
  Back-End/src/main/java/net/scit/backend/workspace/repository/WorkspaceChannelRepository.java
  Back-End/src/main/java/net/scit/backend/workspace/service/WorkspaceChannelService.java
  Back-End/src/main/java/net/scit/backend/workspace/service/impl/WorkspaceChannelServiceImpl.java
Labels: refactor

#234 feat: 채널 번역 등 기능 추가
  Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/index.jsx
  Front-End/bibim/vite/src/views/dm/index.jsx
  Front-End/bibim/vite/src/views/ws-channel/components/ChannelCreateModal.jsx
  Front-End/bibim/vite/src/views/ws-channel/components/ChannelEditModal.jsx
  Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.css
  Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.jsx
Labels: enhancement

#232 refactor: 알림 삭제, 시간 출력방식 리팩토링
  Back-End/src/main/java/net/scit/backend/notification/controller/NotificationController.java
  Back-End/src/main/java/net/scit/backend/notification/service/impl/NotificationServiceImpl.java
  Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/NotificationList.jsx
  Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/index.jsx
Labels: refactor

#231 refactor: schedule/kanbanboard
  .github/workflows/deploy-backend.yml
  Front-End/bibim/vite/src/api/schedule.js
  Front-End/bibim/vite/src/views/schedule/components/Calendar.jsx
  Front-End/bibim/vite/src/views/schedule/components/KanbanBoard.jsx
  Front-End/bibim/vite/src/views/schedule/components/ScheduleDetailModal.jsx
  Front-End/bibim/vite/src/views/schedule/index.jsx
  Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.jsx
  Front-End/bibim/vite/src/views/ws-channel/index.jsx
Labels: enhancement

#236 refactor: 채널 페이지 오류 수정
  Front-End/bibim/vite/src/views/ws-channel/index.jsx
Labels: refactor

#235 feat:ws withdrawal 워크스페이스 나가기 및 나가기 확인 모달창, 마이페이지 워크스페이스 조회, 생성 연결
  Back-End/src/main/java/net/scit/backend/workspace/controller/WorkspaceController.java
  Back-End/src/main/java/net/scit/backend/workspace/event/WorkspaceEvent.java
  Front-End/bibim/vite/src/api/mypage.js
  Front-End/bibim/vite/src/api/workspaceApi.js
  Front-End/bibim/vite/src/views/mypage/component/MyWorkspaces copy.jsx
  Front-End/bibim/vite/src/views/mypage/component/MyWorkspaces.jsx
  Front-End/bibim/vite/src/views/mypage/component/mySchedule.jsx
Labels: enhancement

#237 fix:workdata-photo 자료실 사진 미리보기 깜빡임 문제 수정
  Front-End/bibim/vite/src/views/workdata/components/FileTable.jsx
Labels: bug

#239 refactor: schedule/tag-update-modal
  Back-End/src/main/java/net/scit/backend/schedule/dto/UpdateLargeTagDTO.java
  Back-End/src/main/java/net/scit/backend/schedule/dto/UpdateMediumTagDTO.java
  Back-End/src/main/java/net/scit/backend/schedule/dto/UpdateSmallTagDTO.java
  Back-End/src/main/java/net/scit/backend/schedule/service/impl/ScheduleServiceImpl.java
  Front-End/bibim/vite/src/api/tag.js
  Front-End/bibim/vite/src/views/schedule/components/TagEditModal.jsx
Labels: refactor

#240 feat: 일정관리 관련 구조변경 및 여러 기능 추가
  Front-End/bibim/vite/src/menu-items/utilities.js
  Front-End/bibim/vite/src/ui-component/cards/MainCard4.jsx
  Front-End/bibim/vite/src/views/schedule/components/Calendar.jsx
  Front-End/bibim/vite/src/views/schedule/components/GanttChart.jsx
  Front-End/bibim/vite/src/views/schedule/components/KanbanBoard.jsx
  Front-End/bibim/vite/src/views/schedule/components/ScheduleCreateModal.jsx
  Front-End/bibim/vite/src/views/schedule/components/ScheduleDetailModal.jsx
  Front-End/bibim/vite/src/views/schedule/index.jsx
Labels: enhancement

#241 feat:landing-page
  Front-End/bibim/vite/src/routes/AuthenticationRoutes.jsx
  Front-End/bibim/vite/src/views/landing/components/LandingHeader.jsx
  Front-End/bibim/vite/src/views/landing/index.jsx
  Front-End/bibim/vite/src/views/landing/landing1.jsx
  Front-End/bibim/vite/src/views/landing/landing3.jsx
Labels: enhancement

#243 refactor: 알림 프론트 1차 완성
  Back-End/src/main/java/net/scit/backend/config/SecurityConfig.java
  Back-End/src/main/java/net/scit/backend/jwt/JwtTokenProvider.java
  Back-End/src/main/java/net/scit/backend/member/event/MemberEvent.java
  Back-End/src/main/java/net/scit/backend/member/listener/MemberEventListener.java
  Back-End/src/main/java/net/scit/backend/notification/controller/NotificationController.java
  Back-End/src/main/java/net/scit/backend/notification/service/impl/NotificationServiceImpl.java
  Back-End/src/main/java/net/scit/backend/schedule/event/ScheduleEvent.java
  Back-End/src/main/java/net/scit/backend/schedule/listener/ScheduleEventListener.java
  Back-End/src/main/java/net/scit/backend/workdata/event/WorkdataEvent.java
  Back-End/src/main/java/net/scit/backend/workdata/listener/WorkdataEventListener.java
  Back-End/src/main/java/net/scit/backend/workspace/event/WorkspaceChannelEvent.java
  Back-End/src/main/java/net/scit/backend/workspace/event/WorkspaceEvent.java
  Back-End/src/main/java/net/scit/backend/workspace/listener/WorkspaceChannelEventListener.java
  Back-End/src/main/java/net/scit/backend/workspace/listener/WorkspaceEventListener.java
  Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/NotificationList.jsx
  Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/index.jsx
Labels: bug, enhancement, refactor

#245 feat: env 파일 내용 변경 및 백엔드 배포서버 연결
  Front-End/bibim/vite/src/api/auth.js
  Front-End/bibim/vite/src/api/channel.js
  Front-End/bibim/vite/src/api/members.js
  Front-End/bibim/vite/src/api/workdata.js
  Front-End/bibim/vite/src/api/workspaceApi.js
  Front-End/bibim/vite/src/hooks/useWebSocket.js
  Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/index.jsx
  Front-End/bibim/vite/src/routes/MainRoutes.jsx
  Front-End/bibim/vite/src/views/dm/index.jsx
  Front-End/bibim/vite/src/views/sample-page/index.jsx
  Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.jsx
  Front-End/bibim/vite/vite.config.mjs
Labels: enhancement

#246 feat: 일주일 지난 알림 자동 삭제 구현
  Back-End/src/main/java/net/scit/backend/notification/repository/NotificationRepository.java
  Back-End/src/main/java/net/scit/backend/notification/service/NotificationCleanupService.java
Labels: enhancement

#248 feat: 라우터 수정 및 랜딩 페이지 바로 렌더링
  Front-End/bibim/vite/src/menu-items/utilities.js
  Front-End/bibim/vite/src/routes/AuthenticationRoutes.jsx
  Front-End/bibim/vite/src/routes/LandingRoutes.jsx
  Front-End/bibim/vite/src/routes/MainRoutes.jsx
  Front-End/bibim/vite/src/routes/index.jsx
Labels: enhancement

#249 feat: dm 주소 수정
  Front-End/bibim/vite/src/views/dm/index.jsx
Labels: enhancement

#254 feat: 일정관리 태그 색깔 기능 추가 및 CSS
  Front-End/bibim/vite/package-lock.json
  Front-End/bibim/vite/package.json
  Front-End/bibim/vite/src/api/tag.js
  Front-End/bibim/vite/src/layout/MainLayout/Sidebar/WorkspaceSelector/index.jsx
  Front-End/bibim/vite/src/views/schedule/components/Calendar.jsx
  Front-End/bibim/vite/src/views/schedule/components/KanbanBoard.jsx
  Front-End/bibim/vite/src/views/schedule/components/TagCreateModal.jsx
  Front-End/bibim/vite/yarn.lock
Labels: enhancement

#257 Feat: 읽은/안 읽은 알림 전체 삭제 관련 백,프론트 구현 외 리팩토링 1건
  Back-End/src/main/java/net/scit/backend/config/SecurityConfig.java
  Back-End/src/main/java/net/scit/backend/member/listener/MemberEventListener.java
  Back-End/src/main/java/net/scit/backend/notification/controller/NotificationController.java
  Back-End/src/main/java/net/scit/backend/notification/service/NotificationService.java
  Back-End/src/main/java/net/scit/backend/notification/service/impl/NotificationServiceImpl.java
  Back-End/src/main/java/net/scit/backend/schedule/listener/ScheduleEventListener.java
  Back-End/src/main/java/net/scit/backend/workdata/listener/WorkdataEventListener.java
  Back-End/src/main/java/net/scit/backend/workspace/listener/WorkspaceChannelEventListener.java
  Back-End/src/main/java/net/scit/backend/workspace/listener/WorkspaceEventListener.java
  Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/index.jsx
Labels: enhancement, refactor

#258 refactor/my-workdata
  Back-End/src/main/java/net/scit/backend/mypage/service/impl/MyPageServiceImpl.java
  Back-End/src/main/java/net/scit/backend/workdata/repository/WorkdataRepository.java
Labels: refactor

#259 fix:ws-leace
  Back-End/src/main/java/net/scit/backend/config/SecurityConfig.java
  Front-End/bibim/vite/src/views/ws-select/index.jsx
  Front-End/bibim/vite/src/views/ws-setting/components/LeaveWorkspaceModal.jsx
  Front-End/bibim/vite/src/views/ws-setting/index.jsx
Labels: enhancement

#261 feat: 워크스페이스 디자인 등 프론트엔드 전반 작업
  Front-End/bibim/vite/src/api/workdata.js
  Front-End/bibim/vite/src/assets/images/icons/bibimlogo250318.png
  Front-End/bibim/vite/src/assets/images/icons/bibimsero.png
  Front-End/bibim/vite/src/layout/MainLayout/Header/ProfileSection/index.jsx
  Front-End/bibim/vite/src/views/landing/index.jsx
  Front-End/bibim/vite/src/views/workdata/components/Filter.jsx
  Front-End/bibim/vite/src/views/workdata/index.jsx
  Front-End/bibim/vite/src/views/ws-select/components/CreateWorkspaceModal.jsx
  Front-End/bibim/vite/src/views/ws-select/components/InviteWorkspace.jsx
  Front-End/bibim/vite/src/views/ws-select/components/WorkspaceList.jsx
Labels: enhancement

#260 feat:my-schedule 스케줄 css
  Front-End/bibim/vite/src/api/mypage.js
  Front-End/bibim/vite/src/views/landing/index.jsx
  Front-End/bibim/vite/src/views/mypage/component/MyCalendar.jsx
  Front-End/bibim/vite/src/views/mypage/component/MyGanttChart.jsx
  Front-End/bibim/vite/src/views/mypage/component/MyScheduleDetailModal.jsx
  Front-End/bibim/vite/src/views/mypage/component/MyScheduleEditModal.jsx
  Front-End/bibim/vite/src/views/mypage/component/mySchedule.jsx
  Front-End/bibim/vite/src/views/mypage/index.jsx
  Front-End/bibim/vite/src/views/schedule/components/Calendar.jsx
  Front-End/bibim/vite/src/views/schedule/components/GanttChart.jsx
Labels: enhancement

#262 refactor/signup-default-image
  Back-End/src/main/java/net/scit/backend/config/SecurityConfig.java
  Back-End/src/main/java/net/scit/backend/member/service/impl/MemberServiceImpl.java
Labels: refactor

#265 fix: 채널, dm 프로필 및 닉네임 수정
  Back-End/src/main/java/net/scit/backend/channel/DTO/MessageDTO.java
  Back-End/src/main/java/net/scit/backend/channel/entity/MessageEntity.java
  Back-End/src/main/java/net/scit/backend/channel/service/impl/ChannelServiceImpl.java
  Back-End/src/main/java/net/scit/backend/dm/DTO/DmMessageDTO.java
  Back-End/src/main/java/net/scit/backend/dm/service/impl/DmServiceImpl.java
  Back-End/src/main/java/net/scit/backend/workspace/repository/WorkspaceMemberRepository.java
  Back-End/src/main/java/net/scit/backend/workspace/service/impl/WorkspaceServiceImpl.java
  Front-End/bibim/vite/src/views/dm/index.jsx
  Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.jsx
Labels: bug

#264 feat:my-workdata 마이페이지 내 자료실 추가
  Front-End/bibim/vite/src/layout/MainLayout/Sidebar/index.jsx
  Front-End/bibim/vite/src/views/mypage/component/DeleteStatusModal.jsx
  Front-End/bibim/vite/src/views/mypage/component/FileDetailModal.jsx
  Front-End/bibim/vite/src/views/mypage/component/MyWorkData.jsx
  Front-End/bibim/vite/src/views/mypage/component/mySchedule.jsx
  Front-End/bibim/vite/src/views/mypage/index.jsx
  Front-End/bibim/vite/src/views/schedule/index.jsx
Labels: enhancement

#266 feat: 프론트 디테일
  Back-End/src/main/java/net/scit/backend/schedule/controller/ScheduleController.java
  Front-End/bibim/vite/src/api/schedule.js
  Front-End/bibim/vite/src/api/workspaceApi.js
  Front-End/bibim/vite/src/views/schedule/components/ScheduleDetailModal.jsx
  Front-End/bibim/vite/src/views/schedule/index.jsx
  Front-End/bibim/vite/src/views/ws-select/components/CreateWorkspaceModal.jsx
  Front-End/bibim/vite/src/views/ws-select/components/InviteWorkspace.jsx
  Front-End/bibim/vite/src/views/ws-select/components/WorkspaceList.jsx
Labels: enhancement

#267 refactor: 개별 삭제 시 unreadCount 반영
  Back-End/src/main/java/net/scit/backend/member/listener/MemberEventListener.java
  Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/index.jsx
Labels: bug

#268 refactor: 배포 dev 사이트에서의 SSE Error 테스트 해결책1
  Back-End/src/main/java/net/scit/backend/notification/controller/NotificationController.java
Labels: bug

#269 refactor: SSE 배포 사이트 에러 해결책2
  Back-End/src/main/java/net/scit/backend/notification/controller/NotificationController.java
Labels: bug

#270 refactor: SSE 오류 해결책3
  Back-End/src/main/java/net/scit/backend/notification/controller/NotificationController.java
  Back-End/src/main/java/net/scit/backend/notification/service/NotificationService.java
  Back-End/src/main/java/net/scit/backend/notification/service/impl/NotificationServiceImpl.java
Labels: bug

#271 feat: 일정관리 등 프론트엔드 수정
  Back-End/src/main/java/net/scit/backend/schedule/controller/ScheduleController.java
  Front-End/bibim/vite/src/api/schedule.js
  Front-End/bibim/vite/src/api/tag.js
  Front-End/bibim/vite/src/views/schedule/components/KanbanBoard.jsx
  Front-End/bibim/vite/src/views/schedule/components/ScheduleDetailModal.jsx
  Front-End/bibim/vite/src/views/schedule/index.jsx
Labels: enhancement

#272 feat:ch-user-status 채널 유저 접속현황 조회 기능
  Front-End/bibim/vite/src/views/landing/index.jsx
  Front-End/bibim/vite/src/views/mypage/component/MyWorkData.jsx
  Front-End/bibim/vite/src/views/ws-channel/components/ActiveUsersComponent.css
  Front-End/bibim/vite/src/views/ws-channel/components/ActiveUsersComponent.jsx
  Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.css
  Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.jsx
  Front-End/bibim/vite/src/views/ws-channel/components/MemberStatusModal.jsx
  et --hard ORIG_HEAD
Labels: enhancement

#273 Fix/dm bug
  Back-End/src/main/java/net/scit/backend/workdata/service/impl/WorkdataServiceImpl.java
  Front-End/bibim/vite/src/views/dm/index.jsx
Labels: bug, refactor

#274 fix: 채널 프로필 사진 버그 수정
  Front-End/bibim/vite/src/views/dm/index.jsx
  Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.css
Labels: bug

#275 refactor: 모든 사람에게 알림이 갔다가 알림 아이콘 클릭 시 내 것만 보이는 오류 관련 1트
  Back-End/src/main/java/net/scit/backend/notification/service/impl/NotificationServiceImpl.java
  Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/index.jsx
Labels: bug

#276 fix: 채널/DM 프로필 버그 수정
  Back-End/src/main/java/net/scit/backend/channel/service/impl/ChannelServiceImpl.java
  Back-End/src/main/java/net/scit/backend/dm/DTO/DmMessageDTO.java
  Back-End/src/main/java/net/scit/backend/dm/controller/DMController.java
  Back-End/src/main/java/net/scit/backend/dm/service/impl/DmServiceImpl.java
Labels: bug

#277 refactor: SSE 오류 잡기 2트
  Back-End/src/main/java/net/scit/backend/config/SecurityConfig.java
  Back-End/src/main/java/net/scit/backend/notification/controller/NotificationController.java
  Back-End/src/main/java/net/scit/backend/notification/service/impl/NotificationServiceImpl.java
  Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/index.jsx
Labels: bug

#279 fix: 채널과 디엠 버그 수정
  Back-End/src/main/java/net/scit/backend/channel/service/impl/ChannelServiceImpl.java
  Back-End/src/main/java/net/scit/backend/dm/service/impl/DmServiceImpl.java
  Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.jsx
Labels: bug

#281 feat: 프론트 엔드 전반 기능 및 디자인 수정
  Front-End/bibim/vite/src/api/schedule.js
  Front-End/bibim/vite/src/api/tag.js
  Front-End/bibim/vite/src/views/pages/authentication/Login.jsx
  Front-End/bibim/vite/src/views/schedule/components/Calendar.jsx
  Front-End/bibim/vite/src/views/schedule/components/GanttChart.jsx
  Front-End/bibim/vite/src/views/schedule/components/KanbanBoard.jsx
  Front-End/bibim/vite/src/views/schedule/components/ScheduleDetailModal.jsx
  Front-End/bibim/vite/src/views/schedule/components/TagEditModal.jsx
  Front-End/bibim/vite/src/views/workdata/components/FileCardView.jsx
  Front-End/bibim/vite/src/views/workdata/components/FileTable.jsx
Labels: enhancement

#282 fix:mypage 마이페이지 스케줄&자료실 전반적 수정 (특히 이미지 관련)
  Front-End/bibim/vite/src/api/mypage.js
  Front-End/bibim/vite/src/views/mypage/component/MyCalendar.jsx
  Front-End/bibim/vite/src/views/mypage/component/MyCalendarScheduleDetailModal.jsx
  Front-End/bibim/vite/src/views/mypage/component/MyGanttChart.jsx
  Front-End/bibim/vite/src/views/mypage/component/MyGanttScheduleDetailModal.jsx
  Front-End/bibim/vite/src/views/mypage/component/MyWorkData.jsx
  Front-End/bibim/vite/src/views/mypage/component/mySchedule.jsx
  Front-End/bibim/vite/src/views/mypage/index.jsx
Labels: enhancement

#284 fix:css css 수정
  Front-End/bibim/vite/src/assets/images/icons/bibim250319.png
  Front-End/bibim/vite/src/layout/MainLayout/Header/NotificationSection/index.jsx
  Front-End/bibim/vite/src/layout/MainLayout/Header/index.jsx
  Front-End/bibim/vite/src/layout/MainLayout/MenuList/NavCollapse/index.jsx
  Front-End/bibim/vite/src/layout/MainLayout/MenuList/NavItem/index.jsx
  Front-End/bibim/vite/src/layout/MainLayout/Sidebar/MenuCard/index.jsx
  Front-End/bibim/vite/src/layout/MainLayout/Sidebar/WorkspaceSelector/index.jsx
  Front-End/bibim/vite/src/menu-items/other.js
  Front-End/bibim/vite/src/routes/index.jsx
  Front-End/bibim/vite/src/ui-component/Logo.jsx
  Front-End/bibim/vite/src/views/workdata/components/FileCardView.jsx
  Front-End/bibim/vite/src/views/workdata/components/FileTable.jsx
  Front-End/bibim/vite/src/views/workdata/index.jsx
  Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.css
  Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.jsx
Labels: enhancement

#286 feat: 채널 삭제시 확인 모달 추가
  Front-End/bibim/vite/src/views/ws-channel/components/ChannelEditModal.jsx
  Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.jsx
Labels: enhancement

#290 fix: DM 파일 업로드 버그 수정
  Back-End/src/main/java/net/scit/backend/channel/controller/ChatController.java
  Back-End/src/main/java/net/scit/backend/channel/service/impl/ChannelServiceImpl.java
  Back-End/src/main/java/net/scit/backend/dm/DTO/DmMessageDTO.java
  Back-End/src/main/java/net/scit/backend/dm/controller/DMController.java
  Back-End/src/main/java/net/scit/backend/dm/service/impl/DmServiceImpl.java
  Front-End/bibim/vite/src/views/dm/index.jsx
Labels: bug

#289 feat:auth redirect 비로그인 사용자는 랜딩페이지로
  Front-End/bibim/vite/src/assets/images/icons/bibimlogo250320.png
  Front-End/bibim/vite/src/assets/images/icons/bibimlogo250320_2.png
  Front-End/bibim/vite/src/components/AuthGuard.jsx
  Front-End/bibim/vite/src/layout/MainLayout/Sidebar/MenuCard/index.jsx
  Front-End/bibim/vite/src/routes/MainRoutes.jsx
  Front-End/bibim/vite/src/routes/index.jsx
Labels: enhancement, refactor

#283 feat/summary
  Back-End/build.gradle
  Back-End/src/main/java/net/scit/backend/BackEndApplication.java
  Back-End/src/main/java/net/scit/backend/channel/DTO/ChatRequestDTO.java
  Back-End/src/main/java/net/scit/backend/channel/DTO/SummaryDTO.java
  Back-End/src/main/java/net/scit/backend/channel/component/OpenAiClient.java
  Back-End/src/main/java/net/scit/backend/channel/controller/ChatController.java
  Back-End/src/main/java/net/scit/backend/channel/service/ChannelService.java
  Back-End/src/main/java/net/scit/backend/channel/service/impl/ChannelServiceImpl.java
  Back-End/src/main/java/net/scit/backend/common/component/MailComponents.java
  Back-End/src/main/java/net/scit/backend/common/component/S3Uploader.java
  Back-End/src/main/java/net/scit/backend/common/component/S3UploaderBackUp.java
  Back-End/src/main/java/net/scit/backend/common/config/CacheConfig.java
  Back-End/src/main/java/net/scit/backend/common/config/RedisConfig.java
  Back-End/src/main/java/net/scit/backend/common/config/S3Configuration.java
  Back-End/src/main/java/net/scit/backend/common/config/SecurityConfig.java
  Back-End/src/main/java/net/scit/backend/common/config/WebClientConfig.java
  Back-End/src/main/java/net/scit/backend/common/config/WebSocketConfig.java
  Back-End/src/main/java/net/scit/backend/common/dto/ResultDTO.java
  Back-End/src/main/java/net/scit/backend/common/dto/SuccessDTO.java
  Back-End/src/main/java/net/scit/backend/dm/service/impl/DmServiceImpl.java
  Back-End/src/main/java/net/scit/backend/exception/ErrorCode.java
  Back-End/src/main/java/net/scit/backend/member/controller/MemberController.java
  Back-End/src/main/java/net/scit/backend/member/service/MemberDetailsService.java
  Back-End/src/main/java/net/scit/backend/member/service/MemberService.java
  Back-End/src/main/java/net/scit/backend/member/service/impl/MemberServiceImpl.java
  Back-End/src/main/java/net/scit/backend/mypage/controller/MyPageController.java
  Back-End/src/main/java/net/scit/backend/mypage/dto/MyScheduleDTO.java
  Back-End/src/main/java/net/scit/backend/mypage/service/MyPageService.java
  Back-End/src/main/java/net/scit/backend/mypage/service/impl/MyPageServiceImpl.java
  Back-End/src/main/java/net/scit/backend/oauth/controller/OAuthController.java
  Back-End/src/main/java/net/scit/backend/oauth/service/OAuthService.java
  Back-End/src/main/java/net/scit/backend/oauth/service/impl/OAuthServiceImpl.java
  Back-End/src/main/java/net/scit/backend/schedule/controller/ScheduleController.java
  Back-End/src/main/java/net/scit/backend/schedule/service/ScheduleService.java
  Back-End/src/main/java/net/scit/backend/schedule/service/impl/ScheduleServiceImpl.java
  Back-End/src/main/java/net/scit/backend/workdata/controller/WorkdataController.java
  Back-End/src/main/java/net/scit/backend/workdata/controller/workdataControllerMethodsPart
  Back-End/src/main/java/net/scit/backend/workdata/service/WorkdataService.java
  Back-End/src/main/java/net/scit/backend/workdata/service/impl/WorkdataServiceImpl.java
  Back-End/src/main/java/net/scit/backend/workspace/controller/WorkspaceChannelController.java
  Back-End/src/main/java/net/scit/backend/workspace/controller/WorkspaceController.java
  Back-End/src/main/java/net/scit/backend/workspace/service/WorkspaceChannelService.java
  Back-End/src/main/java/net/scit/backend/workspace/service/WorkspaceService.java
  Back-End/src/main/java/net/scit/backend/workspace/service/impl/WorkspaceChannelServiceImpl.java
  Back-End/src/main/java/net/scit/backend/workspace/service/impl/WorkspaceServiceImpl.java
Labels: enhancement

#292 fix:css 구글 연동 모달창 디자인 수정
  Front-End/bibim/vite/src/views/pages/authentication/LinkAccountModal.jsx
Labels: refactor

#291 refactor/workspace-withdrawal
  Back-End/src/main/java/net/scit/backend/workspace/service/impl/WorkspaceServiceImpl.java
Labels: refactor

#293 feat: 스케줄 생성 및 상세모달 변동사항 바로 칸반보드 반영
  Front-End/bibim/vite/src/views/schedule/components/Calendar.jsx
  Front-End/bibim/vite/src/views/schedule/components/ScheduleCreateModal.jsx
  Front-End/bibim/vite/src/views/schedule/components/ScheduleDetailModal.jsx
  Front-End/bibim/vite/src/views/schedule/components/TagEditModal.jsx
  Front-End/bibim/vite/src/views/schedule/index.jsx
Labels: enhancement

#294 feat: 칸반보드 번역 추가
  Front-End/bibim/vite/src/views/schedule/components/KanbanBoard.jsx
Labels: enhancement

#298 feat: 채널 채팅 요약 기능 추가
  Front-End/bibim/vite/src/api/channel.js
  Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.jsx
  Front-End/bibim/vite/src/views/ws-channel/components/ChatSummaryModal.jsx
  Front-End/bibim/vite/src/views/ws-select/components/WorkspaceList.jsx
Labels: enhancement

#296 fix:css 회원가입창 모달, 스낵바 수정
  Front-End/bibim/vite/src/assets/images/icons/bibimlogo250320_2.png
  Front-End/bibim/vite/src/views/pages/auth-forms/AuthRegister.jsx
Labels: refactor

#297 refactor:workspace-withdrawal
  Back-End/src/main/java/net/scit/backend/workspace/controller/WorkspaceController.java
  Back-End/src/main/java/net/scit/backend/workspace/event/WorkspaceEvent.java
  Back-End/src/main/java/net/scit/backend/workspace/service/WorkspaceService.java
  Back-End/src/main/java/net/scit/backend/workspace/service/impl/WorkspaceServiceImpl.java
Labels: refactor

#301 fix/css3 자료실, 태그 관리, 채널 관리 모달창 css 변경 및 스낵바 추가
  Front-End/bibim/vite/src/views/schedule/components/TagCreateModal.jsx
  Front-End/bibim/vite/src/views/schedule/components/TagEditModal.jsx
  Front-End/bibim/vite/src/views/schedule/index.jsx
  Front-End/bibim/vite/src/views/workdata/index.jsx
  Front-End/bibim/vite/src/views/workdata_create/components/UploadStatusModal.jsx
  Front-End/bibim/vite/src/views/workdata_create/index.jsx
  Front-End/bibim/vite/src/views/ws-channel/components/ChannelCreateModal.jsx
  Front-End/bibim/vite/src/views/ws-channel/components/ChannelEditModal.jsx
Labels: enhancement

#303 fix: 채널 버그 수정
  Back-End/src/main/java/net/scit/backend/channel/service/impl/ChannelServiceImpl.java
  Front-End/bibim/vite/src/views/ws-channel/components/ChatComponent.jsx
Labels: bug
